services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes:
        - .:/app

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" 
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Y2JhYjE1OThlNjdlYmIyZTE2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: .
    command: pytest /app/tests
    environment:
        PYTHONPATH: /app/src/
        POSTGRES_DB: testdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Y2JhYjE1OThlNjdlYmIyZTE2
    depends_on:
      - postgres